# Site
#repository: sanjana-2008/sanjana-2008.github.io
#favicon: images/favicon.ico


# Personal info
name: Sanjana Kulshrestha
title: MS in Computer Information Systems (Data Analytics)
email: sanjana.kul2008@gmail.com
#website: www.github.com/sproogen/resume-theme

# Social links
#twitter_username: facespics
github_username:  sanjana-2008
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: https://www.linkedin.com/in/sanjana-kulshrestha-2008/
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Sanjana Kulshrestha.
  Currently pursuing Master of Science in Computer Information Systems (Data Analytics) from DePaul Univetrsity, Chicago and will be graduating in June 2021.

  I am an experienced professional with having 3.5+ years in software development and Data Analytics. Skilled in Python, SQL, Tableau, Machine Learning, and Databases. 

  I am looking for a Full-time Data Analyst / Data Scientist / Business Intelligence opportunity.

 Expertise:
 • Strategy Analysis
 • Market Basket Analysis
 • Customer Segmentation
 • Time Series Forecasting
 • Predictive Modeling
 • Optimization

Strength
• Ability to solve complex problems and work with multiple data-sets by leveraging relevant tools.
• An effective communicator with strong interpersonal skills
• Collaborate with stakeholders and interact cross-functionally to conduct end-to-end analysis.
• Translate and communicate insights as concrete and actionable recommendations for the business.
  
  Scroll down to learn more about me!

  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   - **Data** **Management**: Database Design and Management, Data Analysis, Pattern and Trend Identification, Visualization and Data Insights, Data Warehousing, Data Mining, Regression Analysis, Data Modeling, Predictive Analytics
   - **Programming** **Languages**: C,C++,Java, SQL
   - **Web Technology**: HTML5, CSS, JavaScript
   - **Data Visualization**: Excel, Tableau, PowerBI, Pentaho CDE
   - **BI and Reporting tools**: MS Power BI, Tableau, Excel VBA, VLOOKUP
   - **Data Analytics**: Excel, R, SQL, Python, Saiku Analytics
   - **Database**: MS Access, Oracle SQL developer, MYSQL, MS SQL
   - **ETL Tools**: MS SSIS, Pentaho
   - **Web Analytics**: Google Analytics
   
# Others Section
# others_title: Achievements & Accomplishments
others_content: | # this will include new lines to allow paragraphs
   - Recipient of “Tech Edge Scholarship”, Illinois Institute of Technology, Chicago
   - Edx HarvardX Data Science: R Basics Certification
   - Interests: Reading Books, Collecting Stamps
   - Volunteer: work as a Community Desk Assistant at IIT dorms.
             


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
