# Personal info
name: Sanjana Kulshrestha
title: MS in Computer Information Systems (Data Analytics)
email: sanjana.kul2008@gmail.com
LinkedIn: https://www.linkedin.com/in/sanjana-kulshrestha-2008
#website: www.github.com/sproogen/resume-theme
# Site
repository: sanjana-2008/sanjana-2008.github.io
#favicon: images/favicon.ico
# Social links
#twitter_username: facespics
github_username:  sanjana-2008
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: https://www.linkedin.com/in/sanjana-kulshrestha-2008
#medium_username: medium.com/@sanjana.kul2008
#youtube_username: globalmtb
# googleplus_username: +jekyll
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - Hi, I am Sanjana Kulshrestha.
  - Currently pursuing Master of Science in Computer Information Systems (Data Analytics) from DePaul Univetrsity, Chicago and will be graduating in June 2021.

  - I am an experienced professional with having 3.5+ years in software development and Data Analytics. Skilled in Python, SQL, Tableau, Machine Learning, and Databases. 
  - I am looking for a Full-time Data Analyst / Data Scientist / Business Intelligence opportunity starting May 2021.
  
  Expertise:
  - Strategy Analysis
  - Market Basket Analysis
  - Customer Segmentation
  - Time Series Forecasting
  - Predictive Modeling
  - System Analysis
  
  Strength:
  - Ability to solve complex problems and work with multiple data-sets by leveraging relevant tools.
  - An effective communicator with strong interpersonal skills
  - Collaborate with stakeholders and interact cross-functionally to conduct end-to-end analysis.
  - Translate and communicate insights as concrete and actionable recommendations for the business.
  - LinkedIn: https://www.linkedin.com/in/sanjana-kulshrestha-2008/
  - Medium: https://medium.com/@sanjana.kul2008

  Scroll down to learn more about me!



more_content: | # this will include new lines to allow paragraphs
   - **Data** **Management**: Database Design and Management, Data Analysis, Pattern and Trend Identification, Visualization and Data Insights, Data Warehousing, Data Mining, Regression Analysis, Data Modeling, Predictive Analytics
   - **Programming** **Languages**: Python, C++, Java, SQL
   - **Data Visualization**: Excel, Tableau, PowerBI.
   - **BI and Reporting tools**: MS Power BI, Tableau, Excel VBA, VLOOKUP, Pivot Table, Macros
   - **Database**: MS Access, Oracle SQL developer, MYSQL, MS SQL
   - **ETL Tools**: MS SSIS, IBM Infosphere Information Server
   - **Web Analytics**: Google Analytics
   - **Statistical and Analytics techniques**: Advanced SQL queries, Regression and Tree-Based Modeling, Hypothesis Testing, A/B Testing, Clustering, Variable Selection, Data Wrangling, and Data Visualization.
   - **Packages**: TensorFlow, PyTorch, Keras, OpenCV, Numpy
   - **Machine Learning Algorithms**: Decision Trees (Random Forests), Clustering (KNN, K-Means), Classification (Naïve Bayes, SVM), Unsupervised learning (PCA), Time Series Analysis, Image Processing, Pattern Recognition, Data Extraction, Business Intelligence (BI)

# Others Section
others_title: Certificates and Leadership
others_content: | # this will include new lines to allow paragraphs
   - Google Analytics Beginner.
   - Google Analytics Advance.
   - AWS certified Data Analytics fundamentals. 
   - SAP Data Intelligence for Enterprise AI.
   - AWS Cloud Practitioner Essentials. 
   - IBM Professional Certificate of Data Science.
   - Lean Six Sigma White Belt. 
   - Project Management Essentials.
   - President of DePaul Information Systems Organization (2020 - 2021)
   - Ex-President of Google Developer Club, DePaul University
   - Social Media Chair of HerCDM, DePaul Uiversity( 2020 - 2021)
   - Global Peer Mentor(2020)
    

   
             


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
